"""
To recreate this file, use this command:

for F in $(ls | grep -v README | grep -v py$); do O=$(echo $F | sed -e 's/.txt//'); echo "'$O' : '$F', "; done >> __init__.py

and then slightly edit this file!
"""


media = {
    'ArgonneLB' : 'ArgonneLB.txt', 
    'MOPS_NoC_2-Deoxy-D-Ribose' : 'MOPS_NoC_2-Deoxy-D-Ribose.txt', 
    'MOPS_NoC_4-Hydroxy-Phenylacetate' : 'MOPS_NoC_4-Hydroxy-Phenylacetate.txt', 
    'MOPS_NoC_Acetic_Acid' : 'MOPS_NoC_Acetic_Acid.txt', 
    'MOPS_NoC_Adenosine' : 'MOPS_NoC_Adenosine.txt', 
    'MOPS_NoC_Adonitol' : 'MOPS_NoC_Adonitol.txt', 
    'MOPS_NoC_Alpha-D-Glucose' : 'MOPS_NoC_Alpha-D-Glucose.txt', 
    'MOPS_NoC_Alpha-D-Lactose' : 'MOPS_NoC_Alpha-D-Lactose.txt', 
    'MOPS_NoC_Cellobiose' : 'MOPS_NoC_Cellobiose.txt', 
    'MOPS_NoC_Citric_Acid' : 'MOPS_NoC_Citric_Acid.txt', 
    'MOPS_NoC_D-Alanine' : 'MOPS_NoC_D-Alanine.txt', 
    'MOPS_NoC_D-Arabinose' : 'MOPS_NoC_D-Arabinose.txt', 
    'MOPS_NoC_D-Arabitol' : 'MOPS_NoC_D-Arabitol.txt', 
    'MOPS_NoC_D-Asparagine' : 'MOPS_NoC_D-Asparagine.txt', 
    'MOPS_NoC_D-Aspartic_Acid' : 'MOPS_NoC_D-Aspartic_Acid.txt', 
    'MOPS_NoC_D-Cysteine' : 'MOPS_NoC_D-Cysteine.txt', 
    'MOPS_NoC_D-Fructose' : 'MOPS_NoC_D-Fructose.txt', 
    'MOPS_NoC_D-Galactose' : 'MOPS_NoC_D-Galactose.txt', 
    'MOPS_NoC_D-Glucosamine' : 'MOPS_NoC_D-Glucosamine.txt', 
    'MOPS_NoC_D-Glucose-6-phosphate' : 'MOPS_NoC_D-Glucose-6-phosphate.txt', 
    'MOPS_NoC_D-Glucose' : 'MOPS_NoC_D-Glucose.txt', 
    'MOPS_NoC_D-Glutamic_Acid' : 'MOPS_NoC_D-Glutamic_Acid.txt', 
    'MOPS_NoC_D-Mannose' : 'MOPS_NoC_D-Mannose.txt', 
    'MOPS_NoC_D-Ribose' : 'MOPS_NoC_D-Ribose.txt', 
    'MOPS_NoC_D-Serine' : 'MOPS_NoC_D-Serine.txt', 
    'MOPS_NoC_D-Xylose' : 'MOPS_NoC_D-Xylose.txt', 
    'MOPS_NoC_Dulcitol' : 'MOPS_NoC_Dulcitol.txt', 
    'MOPS_NoC_Erythritol' : 'MOPS_NoC_Erythritol.txt', 
    'MOPS_NoC_Glycerol' : 'MOPS_NoC_Glycerol.txt', 
    'MOPS_NoC_Glycine' : 'MOPS_NoC_Glycine.txt', 
    'MOPS_NoC_Inosine' : 'MOPS_NoC_Inosine.txt', 
    'MOPS_NoC_L-Alanine' : 'MOPS_NoC_L-Alanine.txt', 
    'MOPS_NoC_L-Arabinose' : 'MOPS_NoC_L-Arabinose.txt', 
    'MOPS_NoC_L-Arabitol' : 'MOPS_NoC_L-Arabitol.txt', 
    'MOPS_NoC_L-Asparagine' : 'MOPS_NoC_L-Asparagine.txt', 
    'MOPS_NoC_L-Aspartic_Acid' : 'MOPS_NoC_L-Aspartic_Acid.txt', 
    'MOPS_NoC_L-Cysteic_Acid' : 'MOPS_NoC_L-Cysteic_Acid.txt', 
    'MOPS_NoC_L-Cysteine' : 'MOPS_NoC_L-Cysteine.txt', 
    'MOPS_NoC_L-Fucose' : 'MOPS_NoC_L-Fucose.txt', 
    'MOPS_NoC_L-Glutamic_Acid' : 'MOPS_NoC_L-Glutamic_Acid.txt', 
    'MOPS_NoC_L-Glutamine' : 'MOPS_NoC_L-Glutamine.txt', 
    'MOPS_NoC_L-Isoleucine' : 'MOPS_NoC_L-Isoleucine.txt', 
    'MOPS_NoC_L-Leucine' : 'MOPS_NoC_L-Leucine.txt', 
    'MOPS_NoC_L-Lysine' : 'MOPS_NoC_L-Lysine.txt', 
    'MOPS_NoC_L-Methionine' : 'MOPS_NoC_L-Methionine.txt', 
    'MOPS_NoC_L-Phenylalanine' : 'MOPS_NoC_L-Phenylalanine.txt', 
    'MOPS_NoC_L-Pyro-Glutamic_Acid' : 'MOPS_NoC_L-Pyro-Glutamic_Acid.txt', 
    'MOPS_NoC_L-Rhamnose' : 'MOPS_NoC_L-Rhamnose.txt', 
    'MOPS_NoC_L-Serine' : 'MOPS_NoC_L-Serine.txt', 
    'MOPS_NoC_L-Sorbose' : 'MOPS_NoC_L-Sorbose.txt', 
    'MOPS_NoC_L-Threonine' : 'MOPS_NoC_L-Threonine.txt', 
    'MOPS_NoC_L-Tryptophan' : 'MOPS_NoC_L-Tryptophan.txt', 
    'MOPS_NoC_L-Valine' : 'MOPS_NoC_L-Valine.txt', 
    'MOPS_NoC_L-Xylose' : 'MOPS_NoC_L-Xylose.txt', 
    'MOPS_NoC_Lactic_Acid' : 'MOPS_NoC_Lactic_Acid.txt', 
    'MOPS_NoC_Lactulose' : 'MOPS_NoC_Lactulose.txt', 
    'MOPS_NoC_Malic_Acid' : 'MOPS_NoC_Malic_Acid.txt', 
    'MOPS_NoC_Melibiose' : 'MOPS_NoC_Melibiose.txt', 
    'MOPS_NoC_Myo-Inositol' : 'MOPS_NoC_Myo-Inositol.txt', 
    'MOPS_NoC_Negative_Control' : 'MOPS_NoC_Negative_Control.txt', 
    'MOPS_NoC_Oxalic_Acid' : 'MOPS_NoC_Oxalic_Acid.txt', 
    'MOPS_NoC_Potassium_Sorbate' : 'MOPS_NoC_Potassium_Sorbate.txt', 
    'MOPS_NoC_Propionate' : 'MOPS_NoC_Propionate.txt', 
    'MOPS_NoC_Putrescine' : 'MOPS_NoC_Putrescine.txt', 
    'MOPS_NoC_Pyruvate' : 'MOPS_NoC_Pyruvate.txt', 
    'MOPS_NoC_Quinate' : 'MOPS_NoC_Quinate.txt', 
    'MOPS_NoC_Raffinose' : 'MOPS_NoC_Raffinose.txt', 
    'MOPS_NoC_Salicoside' : 'MOPS_NoC_Salicoside.txt', 
    'MOPS_NoC_Succinate' : 'MOPS_NoC_Succinate.txt', 
    'MOPS_NoC_Sucrose' : 'MOPS_NoC_Sucrose.txt', 
    'MOPS_NoC_Thymidine' : 'MOPS_NoC_Thymidine.txt', 
    'MOPS_NoC_Trehalose' : 'MOPS_NoC_Trehalose.txt', 
    'MOPS_NoC_Xylitol' : 'MOPS_NoC_Xylitol.txt', 
    'MOPS_NoN_Adenine' : 'MOPS_NoN_Adenine.txt', 
    'MOPS_NoN_Adenosine' : 'MOPS_NoN_Adenosine.txt', 
    'MOPS_NoN_Allantoin' : 'MOPS_NoN_Allantoin.txt', 
    'MOPS_NoN_Beta-Phenylethylamine' : 'MOPS_NoN_Beta-Phenylethylamine.txt', 
    'MOPS_NoN_Biuret' : 'MOPS_NoN_Biuret.txt', 
    'MOPS_NoN_Cytidine' : 'MOPS_NoN_Cytidine.txt', 
    'MOPS_NoN_Cytosine' : 'MOPS_NoN_Cytosine.txt', 
    'MOPS_NoN_D-Methionine' : 'MOPS_NoN_D-Methionine.txt', 
    'MOPS_NoN_D-Valine' : 'MOPS_NoN_D-Valine.txt', 
    'MOPS_NoN_Glycine' : 'MOPS_NoN_Glycine.txt', 
    'MOPS_NoN_Guanidine' : 'MOPS_NoN_Guanidine.txt', 
    'MOPS_NoN_Histamine' : 'MOPS_NoN_Histamine.txt', 
    'MOPS_NoN_Inosine' : 'MOPS_NoN_Inosine.txt', 
    'MOPS_NoN_L-Arginine' : 'MOPS_NoN_L-Arginine.txt', 
    'MOPS_NoN_L-Glutathione' : 'MOPS_NoN_L-Glutathione.txt', 
    'MOPS_NoN_L-Histidine' : 'MOPS_NoN_L-Histidine.txt', 
    'MOPS_NoN_L-Proline' : 'MOPS_NoN_L-Proline.txt', 
    'MOPS_NoN_L-Pyro-Glutamic_Acid' : 'MOPS_NoN_L-Pyro-Glutamic_Acid.txt', 
    'MOPS_NoN_N-Acetyl-D-Glucosamine' : 'MOPS_NoN_N-Acetyl-D-Glucosamine.txt', 
    'MOPS_NoN_Negative_Control' : 'MOPS_NoN_Negative_Control.txt', 
    'MOPS_NoN_Thiourea' : 'MOPS_NoN_Thiourea.txt', 
    'MOPS_NoN_Thymine' : 'MOPS_NoN_Thymine.txt', 
    'MOPS_NoN_Tyramine' : 'MOPS_NoN_Tyramine.txt', 
    'MOPS_NoN_Uridine' : 'MOPS_NoN_Uridine.txt'
}
