from external_reactions import uptake_and_secretion_reactions, remove_uptake_and_secretion_reactions
from create_stoichiometric_matrix import create_stoichiometric_matrix
from bounds import reaction_bounds, compound_bounds